### ISSUE TITLE
Issue with sitkImageFileReader.cxx.o while building for Linux aarch 64

### ISSUE THREAD

**Issue by LightEssembly** [SimpleITK/SimpleITKPythonPackage#47]
Hi everyone,

I have got a Nvidia Jetson TX2 with the following specs:
Processor: ARMv8 rev 3 (v8l) x 4
Graphics: NVIDIA Tegra X2
GNOME: 3.28.2
OS Type: 64 bit

After having no luck installing SimpleITK with pip, I have attempted building it with following code that I took from [here](https://github.com/SimpleITK/SimpleITKPythonPackage):
`pip install git+https://github.com/SimpleITK/SimpleITKPythonPackage.git -v`

The installation almost finished but then it produced the following error:
`    [961/974] Building CXX object Code/BasicFilters/src/CMakeFiles/SimpleITK_ITKWatersheds.dir/sitkMorphologicalWatershedFromMarkersImageFilter.cxx.o
    [962/974] Building CXX object Code/BasicFilters/src/CMakeFiles/SimpleITK_SimpleITKFilters.dir/sitkPasteImageFilter.cxx.o
    [963/974] Building CXX object Code/IO/src/CMakeFiles/SimpleITKIO.dir/sitkImageFileReader.cxx.o
    ninja: build stopped: subcommand failed.
    FAILED: SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build /tmp/pip-pctnm39_-build/_skbuild/linux-aarch64-3.6/cmake-build/sitk-sb/SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build
    cd /tmp/pip-pctnm39_-build/_skbuild/linux-aarch64-3.6/cmake-build/sitk-sb/SimpleITK-build && /home/tentacools/.local/lib/python3.6/site-packages/cmake/data/bin/cmake --build . && /home/tentacools/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -E touch /tmp/pip-pctnm39_-build/_skbuild/linux-aarch64-3.6/cmake-build/sitk-sb/SimpleITK-prefix/src/SimpleITK-stamp/SimpleITK-build
    ninja: build stopped: subcommand failed.
    FAILED: SimpleITK-superbuild-prefix/src/SimpleITK-superbuild-stamp/SimpleITK-superbuild-build /tmp/pip-pctnm39_-build/_skbuild/linux-aarch64-3.6/cmake-build/SimpleITK-superbuild-prefix/src/SimpleITK-superbuild-stamp/SimpleITK-superbuild-build
    cd /tmp/pip-pctnm39_-build/_skbuild/linux-aarch64-3.6/cmake-build/sitk-sb && /home/tentacools/.local/lib/python3.6/site-packages/cmake/data/bin/cmake --build . && /home/tentacools/.local/lib/python3.6/site-packages/cmake/data/bin/cmake -E touch /tmp/pip-pctnm39_-build/_skbuild/linux-aarch64-3.6/cmake-build/SimpleITK-superbuild-prefix/src/SimpleITK-superbuild-stamp/SimpleITK-superbuild-build
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/home/tentacools/Desktop/bronchinet/bronvenv/lib/python3.6/site-packages/skbuild/setuptools_wrap.py", line 593, in setup
        cmkr.make(make_args, env=env)
      File "/home/tentacools/Desktop/bronchinet/bronvenv/lib/python3.6/site-packages/skbuild/cmaker.py", line 515, in make
        os.path.abspath(CMAKE_BUILD_DIR())))

    An error occurred while building with CMake.
      Command:
        cmake --build . --target install --config Release --
      Source directory:
        /tmp/pip-pctnm39_-build
      Working directory:
        /tmp/pip-pctnm39_-build/_skbuild/linux-aarch64-3.6/cmake-build
    Please see CMake's output for more information.
error
Cleaning up...
  Removing source in /tmp/pip-pctnm39_-build
Command "/home/tentacools/Desktop/bronchinet/bronvenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-pctnm39_-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4m65moo9-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/tentacools/Desktop/bronchinet/bronvenv/include/site/python3.6/SimpleITK" failed with error code 1 in /tmp/pip-pctnm39_-build/
Exception information:
Traceback (most recent call last):
  File "/home/tentacools/Desktop/bronchinet/bronvenv/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/tentacools/Desktop/bronchinet/bronvenv/lib/python3.6/site-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/home/tentacools/Desktop/bronchinet/bronvenv/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/tentacools/Desktop/bronchinet/bronvenv/lib/python3.6/site-packages/pip/req/req_install.py", line 878, in install
    spinner=spinner,
  File "/home/tentacools/Desktop/bronchinet/bronvenv/lib/python3.6/site-packages/pip/utils/__init__.py", line 725, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "/home/tentacools/Desktop/bronchinet/bronvenv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-pctnm39_-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4m65moo9-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/tentacools/Desktop/bronchinet/bronvenv/include/site/python3.6/SimpleITK" failed with error code 1 in /tmp/pip-pctnm39_-build/
`

Does anyone have any ideas of what this is or can be related to?
Thanks in advance!

**Comment by zivy** [comment]
Hello @LightEssembly,

Not sure about the error. Please note that the code you are using is not what is recommended for manual building and language wrapping, that process is described [here](https://simpleitk.readthedocs.io/en/master/building.html).

I don't think that is the problem here, possibly @blowekamp  can comment.
